<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Avg. (s)' => '',
  'Callstack' => '',
  'Connection ID' => '',
  'Count' => '',
  'Max. (s)' => '',
  'Min. (s)' => '',
  'Mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => '',
  'No SQL queries were recorded during this request or profiling the SQL is DISABLED.' => '',
  'Query' => '',
  'Servers' => '',
  'Summary' => '',
  'The %class% class must be compatible with YiiDebugToolbarPanelInterface' => '',
  'Time (s)' => '',
  'Total (s)' => '',
);
